### ISSUE TITLE
Unification of UI

### ISSUE THREAD

**Issue by samuelgrant** [Kaezon/EVERoachCoach#10]
Make the add stock and order buttons modal forms like the add more stock it looks so much nicer GUI wise and is cleaner

**Comment by Kaezon** [comment]
This is confusing. Can you clarify?

**Comment by samuelgrant** [comment]
make the Add new stock form and the add order form a modal form like the add more stock form

**Comment by Kaezon** [comment]
Completed in commit b7816c5

**Comment by samuelgrant** [comment]
Thankyou!
