### ISSUE TITLE
Handle orders exceeding the stock count correctly

### ISSUE THREAD

**Issue by Kaezon** [Kaezon/EVERoachCoach#15]
Right now the server just throws an internal error.

**Comment by samuelgrant** [comment]
At the moment if i have 20 of an item and 20 in stock it errors can we make it error at 21 requested if 20 are in stock as a temporary fix?

**Comment by Kaezon** [comment]
I probably used the wrong comparison operator in the view. I need to make
the error modal and JS fail function for this anyways.
