### ISSUE TITLE
Buyers Dashboard

### ISSUE THREAD

**Issue by samuelgrant** [Kaezon/EVERoachCoach#18]
Can the buyer have a dashboard, here they can see stock available @ price, place orders and see the status i.e. paid not paid. And their recent stocks!

**Comment by Kaezon** [comment]
This is now a subtask of #6

**Comment by samuelgrant** [comment]
Can we add tags to items, so that buyers can look for things based on groups, ie void, null, antimatter might be tagged Vindi - nanite might be tagged Other, Nightmare Vindi, etc and if someone in the buy page they can search for items based on groups
